# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=26.1.2-1.0.0
group=net.xalcon.torchmaster
java_version=25

# Common
minecraft_version=26.1.2
mod_name=Torchmaster
mod_author=Xalcon
mod_id=torchmaster
license=MIT
credits=
description=Special lamp and torch which prevents mob spawning.
minecraft_version_range_neoforge=[26.1.2]
minecraft_version_range_fabric=>=1.21.11 <=1.21.11
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions

# Fabric - https://fabricmc.net/develop/
fabric_version=0.141.1+1.21.11
fabric_loader_version=0.18.4
loom_version=1.13-SNAPSHOT

# https://github.com/wisp-forest/owo-lib/releases
owo_version=0.12.24+1.21.9
# https://github.com/TerraformersMC/ModMenu/releases
modmenu_version=17.0.0-beta.2

# NeoForge - https://neoforged.net/
neoforge_version=26.1.2.109
neoforge_loader_version_range=[4,)
# https://projects.neoforged.net/neoforged/moddevgradle
neoforge_moddev_version=2.0.147

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
